import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Hader from "@/Components/Hader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dev-Story",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Hader></Hader>
        <main className=" px-5 py-5">{children}</main>
      </body>
    </html>
  );
}
